version: "3.9"
services:
  db:
    image: postgres:17
    container_name: lmexpense_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lmexpense-user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: lmexpense-db
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pg17_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lmexpense-user -d lmexpense-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg17_data:
